### ISSUE TITLE
[GUI] Design new GUI to match mockup

### ISSUE THREAD

**Issue by yong24s** [CS2103JAN2017-W13-B1/main#56]
- [x] Setup and Test JFoenix Theming Library
- [x] Ascertain JFoenix fits our needs and usages by creating proof-of-concepts
- [x] Create new or Morph existing UI elements to new design
- [x] Ensure new GUI has exact behaviour as the former

**Comment by yong24s** [comment]
**Create new or Morph existing UI elements to new design**

Morphed UI checklist

- [ ] CommandBox


To be updated...
